# Generated by Django 5.0.7 on 2024-08-08 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z- A-z]+$', code='Invalid name', message='Invalid data format. Only alphabetic are allowed.')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z- A-z]+$', code='Invalid name', message='Invalid data format. Only alphabetic are allowed.')])),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z- A-z 0-9]+$', code='Invalide name', message='Invalid data format. Only letters, numbers, and hyphens are allowed.')])),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('((98)|(97))(\\d){8}', message="Please enter a valid Nepali phone number starting with '98' or '97' and consisting of 10 digits.")])),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'user')], max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
