# Generated by Django 5.0.7 on 2024-08-16 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CafeCms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="photos/")),
                (
                    "email_no1",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="E-mail"
                    ),
                ),
                ("email_2", models.EmailField(max_length=255, unique=True)),
                ("email_3", models.EmailField(max_length=255, unique=True)),
                (
                    "mobile_no1",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid mobile number",
                                regex="^98\\d{8}$|^97\\d{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "mobile_no2",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid mobile number",
                                regex="^98\\d{8}$|^97\\d{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "phone_no3",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid mobile number",
                                regex="^98\\d{8}$|^97\\d{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid  telephone number",
                                regex="^0\\d{1,2}\\d{6,7}$",
                            )
                        ],
                    ),
                ),
                ("location", models.CharField(max_length=255)),
            ],
        ),
    ]
