# Generated by Django 5.0.7 on 2024-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cafecms",
            old_name="email_no1",
            new_name="email_1",
        ),
        migrations.RenameField(
            model_name="cafecms",
            old_name="phone_no3",
            new_name="mobile_no3",
        ),
        migrations.AlterField(
            model_name="cafecms",
            name="email_2",
            field=models.EmailField(max_length=255, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="cafecms",
            name="email_3",
            field=models.EmailField(max_length=255, unique=True, verbose_name="E-mail"),
        ),
    ]
