# Generated by Django 5.0.7 on 2024-08-16 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_rename_email_no1_cafecms_email_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafecms",
            name="mobile_no1",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid mobile number",
                        regex="^98\\d{8}$|^97\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cafecms",
            name="mobile_no2",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid mobile number",
                        regex="^98\\d{8}$|^97\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cafecms",
            name="mobile_no3",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid mobile number",
                        regex="^98\\d{8}$|^97\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cafecms",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid telephone number",
                        regex="^0\\d{1,2}\\d{6,7}$",
                    )
                ],
            ),
        ),
    ]
